// Build information, automatically generated by `ng-info`
const build = {
    version: "1.1.0",
    timestamp: "Thu Apr 18 2024 15:37:01 GMT+0200 (Central European Summer Time)",
    message: null,
    git: {
        user: "Asier de Diego",
        branch: "master",
        hash: "b7bd1f",
        fullHash: "b7bd1f7fa65fa15a14ae85148e53909a04394c0a"
    }
};

export default build;