// Build information, automatically generated by `ng-info`
const build = {
    version: "1.0.0",
    timestamp: "Thu Apr 18 2024 11:11:31 GMT+0200 (Central European Summer Time)",
    message: null,
    git: {
        user: "Asier de Diego",
        branch: "master",
        hash: "3bcf3e",
        fullHash: "3bcf3ea6395613c8b970677db09662f3b27fc95a"
    }
};

export default build;